/* Real production UI with scoped API stubs. No account data or business writes. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium, expect } = require('playwright/test');
const root = path.resolve(__dirname, '..'), assets = path.join(root, 'webui_new/static');
const output = path.join(root, 'tmp/personal-profile-qa-20261004');
const preview = process.argv.includes('--preview');
fs.mkdirSync(output, { recursive: true });
const blank = () => ({ schema_version: 1, basic_info: { real_name: null, institution: '重庆大学', department: null, personnel_category: null, employee_number: null, student_number: null, gender: null, birth_date: null, nationality: null },
    policy_identity: { professional_title_level: null, professional_position_grade: null, staff_grade: null, administrative_rank: null, academician_status: null, nationally_recognized_expert: null }, funding: { default_project_id: null, projects: [] }, settlement: { has_official_card: null } });
(async () => {
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, ...(preview ? { recordVideo: { dir: output, size: { width: 1440, height: 1000 } } } : {}) });
        let record = { profile: blank(), revision: 0, onboarding_status: 'pending' }, writes = [], failSave = false;
        const errors = [];
        page.on('pageerror', err => errors.push(err.message));
        await page.addInitScript(() => { localStorage.setItem('hommey.access_token', 'test.' + btoa(JSON.stringify({ sub: 'qa', exp: 9999999999 })) + '.test'); localStorage.setItem('hommey.theme', 'light'); });
        await page.route('**/*', async route => {
            const req = route.request(), pathname = new URL(req.url()).pathname;
            if (pathname.startsWith('/static/')) {
                const file = path.resolve(assets, '.' + pathname.slice('/static'.length));
                if (!file.startsWith(assets + path.sep) || !fs.existsSync(file)) return route.fulfill({ status: 404 });
                return route.fulfill({ body: fs.readFileSync(file), contentType: ({ '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml' })[path.extname(file)] || 'application/octet-stream' });
            }
            if (pathname === '/chat/qa') return route.fulfill({ contentType: 'text/html; charset=utf-8', body: fs.readFileSync(path.join(root, 'webui_new/templates/chat.html'), 'utf8').replaceAll('{{ user_id }}', 'qa').replaceAll("{{ user_id[0:1].upper() if user_id else 'U' }}", 'Q') });
            if (pathname.endsWith('/profile') || pathname.endsWith('/profile/skip')) {
                if (req.method() !== 'GET') {
                    const body = req.postDataJSON();
                    if (failSave) return route.fulfill({ status: 500, json: { error: { code: 'PROFILE_UNAVAILABLE', message: '个人资料暂时无法保存' } } });
                    if (body.revision !== record.revision) return route.fulfill({ status: 409, json: { error: { code: 'PROFILE_CONFLICT', message: '资料已在另一页面更新，请重新打开后编辑' } } });
                    writes.push(body);
                    record = { ...record, profile: body.profile || record.profile, revision: record.revision + 1, onboarding_status: body.profile ? 'completed' : 'skipped' };
                }
                return route.fulfill({ json: record });
            }
            let body = {};
            if (pathname.endsWith('/status')) body = { initialized: true };
            if (pathname.endsWith('/sessions')) body = { sessions: [] };
            if (pathname.endsWith('/summary')) body = { name_display: 'qa', role: 'user', preferences: [] };
            if (pathname.endsWith('/trip/active')) body = { active_trip: null };
            return route.fulfill({ json: body });
        });
        const dialog = page.locator('#personalProfileLayer');
        const openSettings = async () => { await page.locator(page.viewportSize().width <= 760 ? '#mobileHandle' : '#sidebarToggle').click(); await page.locator('#settingsButton').click(); };
        const openProfile = async step => {
            await page.locator(`[data-settings-section="${step}"]`).click();
            await page.locator(`[data-profile-step="${step}"]`).click();
        };
        const tab = key => page.locator(`#personalProfileTabs [data-step="${key}"]`);
        const save = page.locator('#personalProfileSave');
        const project = index => page.locator('.profile-page > .profile-project').nth(index);
        const expandProject = async index => { await project(index).locator('.profile-project-toggle').click(); await expect(page.locator(`#project-${index}-name`)).toBeVisible(); };
        await page.goto('http://hommey.test/chat/qa');
        await expect(dialog).toHaveClass(/open/);
        if (preview) {
            await page.waitForTimeout(750);
            await page.locator('#profile-personnel_category').selectOption('student');
            await page.waitForTimeout(700);
            await page.locator('#profile-real_name').fill('何靖');
            await page.locator('#profile-student_number').fill('000123');
            await page.locator('#profile-gender').selectOption('male');
            await page.locator('.profile-more summary').click();
            await page.waitForTimeout(650);
            await page.locator('.profile-more summary').click();
            await page.waitForTimeout(650);
            await save.click();
            await page.waitForTimeout(700);
            await page.locator('#profileAddProject').click();
            await page.waitForTimeout(700);
            await page.locator('#project-0-name').fill('科研课题 A');
            await page.locator('#project-0-funding_category').selectOption('research');
            await page.waitForTimeout(850);
            await page.locator('#project-0-funding_category').selectOption('non_research');
            await page.waitForTimeout(750);
            await project(0).locator('.profile-project-done').click();
            await page.waitForTimeout(700);
            await project(0).locator('.profile-project-toggle').click();
            await page.waitForTimeout(700);
            await project(0).getByRole('button', { name: '移除项目 1' }).click();
            await page.waitForTimeout(750);
            await page.locator('#personalProfileBack').click();
            await page.waitForTimeout(850);
            await page.locator('#personalProfileSkip').click();
            await page.waitForTimeout(650);
            const video = page.video(); await page.close();
            await video.saveAs(path.join(output, 'profile-motion-preview.webm'));
            console.log('Saved profile-motion-preview.webm');
            return;
        }
        // Freeze real animations at several times and compare rendered geometry.
        // This verifies continuity, rather than merely checking a CSS duration exists.
        const finish = () => page.evaluate(() => document.getElementById('personalProfileLayer').getAnimations({ subtree: true }).forEach(animation => animation.finish()));
        const frame = time => page.evaluate(time => {
            document.getElementById('personalProfileLayer').getAnimations({ subtree: true }).forEach(animation => { animation.pause(); animation.currentTime = time; });
            const rect = document.getElementById('profile-department').getBoundingClientRect();
            return { left: rect.left, top: rect.top, height: document.getElementById('personalProfileForm').offsetHeight,
                opacity: Number(getComputedStyle(document.getElementById('profile-student_number').parentElement).opacity) };
        }, time);
        await finish();
        const original = await page.evaluate(() => ({ left: document.getElementById('profile-department').getBoundingClientRect().left, top: document.getElementById('profile-department').getBoundingClientRect().top, height: document.getElementById('personalProfileForm').offsetHeight }));
        await page.evaluate(() => { const select = document.getElementById('profile-personnel_category'); select.value = 'student'; select.dispatchEvent(new Event('change')); });
        const start = await frame(0);
        assert(Math.abs(start.left - original.left) < 2, 'retained fields must start at their previous position');
        assert(Math.abs(start.top - original.top) < 2, 'retained rows must not jump');
        assert(Math.abs(start.height - original.height) < 2, 'modal height must not jump');
        assert(start.opacity < .05, 'new fields must start faded');
        const middle = await frame(80);
        await page.screenshot({ path: path.join(output, 'motion-mid-reflow.png') });
        await finish();
        const end = await page.evaluate(() => ({ left: document.getElementById('profile-department').getBoundingClientRect().left, top: document.getElementById('profile-department').getBoundingClientRect().top, height: document.getElementById('personalProfileForm').offsetHeight, opacity: Number(getComputedStyle(document.getElementById('profile-student_number').parentElement).opacity) }));
        assert(middle.top < start.top - 2 && middle.top > end.top + 2, 'rows must pass through intermediate positions');
        assert(Math.abs(middle.left - start.left) < 1 && Math.abs(end.left - start.left) < 1, 'basic fields must keep their columns without crossing');
        assert(middle.height > start.height && middle.height < end.height, 'modal must resize continuously');
        assert(middle.opacity > 0 && middle.opacity < 1 && end.opacity === 1);
        await page.evaluate(() => document.querySelector('.profile-more summary').click());
        await page.evaluate(() => document.getElementById('personalProfileLayer').getAnimations({ subtree: true }).forEach(animation => { animation.pause(); animation.currentTime = 80; }));
        const partialHeight = await page.locator('.profile-more-body').evaluate(body => body.getBoundingClientRect().height);
        assert(partialHeight > 0);
        await page.evaluate(() => document.querySelector('.profile-more summary').click());
        const reversedHeight = await page.locator('.profile-more-body').evaluate(body => {
            body.getAnimations().forEach(animation => { animation.pause(); animation.currentTime = 0; });
            return body.getBoundingClientRect().height;
        });
        assert(Math.abs(reversedHeight - partialHeight) < 2, 'rapid disclosure reversal must continue from its visible height');
        await finish();
        await expect(page.locator('.profile-more')).not.toHaveAttribute('open', '');
        await page.locator('#profile-personnel_category').selectOption('staff');
        await page.locator('#profile-personnel_category').selectOption('student');
        await page.locator('#profile-personnel_category').selectOption('staff');
        await page.locator('#profile-personnel_category').selectOption('student');
        await finish();
        assert(await page.evaluate(() => { const ids = [...document.querySelectorAll('[id]')].map(node => node.id); return ids.length === new Set(ids).size; }));
        await expect(page.locator('[data-profile-ghost]')).toHaveCount(0);
        console.log('PASS intermediate field positions, continuous modal height, fade-in and rapid animation reversal');
        await page.screenshot({ path: path.join(output, 'initial-desktop.png'), animations: 'disabled' });
        await page.locator('#profile-personnel_category').selectOption('student');
        await expect(page.locator('#profile-student_number')).toBeVisible();
        await expect(page.locator('#profile-employee_number')).toHaveCount(0);
        await expect(tab('identity')).toHaveCount(0);
        await page.locator('#profile-student_number').fill('000123');
        await page.locator('#profile-real_name').fill('小林');
        await page.locator('#profile-gender').selectOption('female');
        await save.click();
        await expect(tab('funding')).toHaveAttribute('aria-current', 'step');
        await page.locator('#profileAddProject').click();
        await page.locator('#project-0-name').fill('科研课题 A');
        await page.locator('#project-0-funding_category').selectOption('research');
        await page.locator('#project-0-research_type').selectOption('vertical');
        await page.locator('#project-0-program_type').selectOption('national_social_science');
        await page.locator('#project-0-financial_project_code').fill('000987');
        await page.locator('#project-0-funding_source').selectOption('fiscal');
        await page.locator('#project-0-is_military_project').selectOption('false');
        await page.locator('.profile-project-default input').check();
        await project(0).locator('.profile-project-done').click();
        await expect(page.locator('#project-0-name')).toBeHidden();
        await expect(project(0).locator('.profile-project-toggle')).toHaveAttribute('aria-expanded', 'false');
        await expect(project(0).locator('h4')).toHaveText('科研课题 A');
        await expect(project(0).locator('.profile-project-meta')).toHaveText('纵向科研 · 财政拨款 · 经费号 000987');
        assert((await project(0).boundingBox()).height < 110, 'completed funding cards should be compact');
        assert.equal(writes.length, 0, 'finishing a card must retain a draft until the page is saved');
        await expandProject(0);
        await expect(page.locator('#project-0-financial_project_code')).toHaveValue('000987');
        await expect(page.locator('#project-0-program_type')).toHaveValue('national_social_science');
        await expect(page.locator('#project-0-is_military_project')).toHaveValue('false');
        await project(0).locator('.profile-project-toggle').click();
        await expect(page.locator('#project-0-name')).toBeHidden();
        await page.locator('#profileAddProject').click();
        await page.locator('#project-1-name').fill('教学经费');
        await page.locator('#project-1-funding_category').selectOption('non_research');
        await page.locator('#project-1-funding_source').selectOption('non_fiscal');
        await project(1).locator('.profile-project-done').click();
        await expect(page.locator('#project-1-name')).toBeHidden();
        await page.screenshot({ path: path.join(output, 'funding-compact-desktop.png'), animations: 'disabled' });
        await save.click();
        await expect(dialog).not.toHaveClass(/open/);
        assert.equal(record.profile.basic_info.student_number, '000123');
        assert.equal(record.profile.basic_info.gender, 'female');
        assert.equal(record.profile.policy_identity.staff_grade, null);
        assert.equal(record.profile.funding.projects[0].financial_project_code, '000987');
        assert.equal(record.profile.funding.projects.length, 2);
        assert.equal(record.profile.funding.default_project_id, record.profile.funding.projects[0].id);
        console.log('PASS student setup, compact cards, draft retention, multiple funding projects and default selection');
        await page.reload();
        await expect(page.locator('#initOverlay')).toBeHidden();
        await expect(page.locator('#profileBasicSummary')).toHaveText('学生');
        await expect(dialog).not.toHaveClass(/open/);
        await openSettings();
        await expect(page.locator('#profileIdentityEntry')).toBeHidden();
        await page.screenshot({ path: path.join(output, 'settings-student.png'), animations: 'disabled' });
        await openProfile('basic');
        await expect(page.locator('#profile-student_number')).toHaveValue('000123');
        await page.locator('#profile-personnel_category').selectOption('staff');
        await expect(page.locator('#profile-employee_number')).toBeVisible();
        await page.locator('#profile-employee_number').fill('000789');
        await tab('identity').click();
        await page.locator('#profile-professional_title_level').selectOption('senior');
        await page.locator('#profile-professional_position_grade').fill('2');
        await page.locator('#profile-staff_grade').fill('3');
        await page.screenshot({ path: path.join(output, 'staff-identity.png'), animations: 'disabled' });
        await save.click();
        await expect(dialog).not.toHaveClass(/open/);
        assert.equal(record.profile.policy_identity.professional_position_grade, 2);
        assert.equal(record.profile.basic_info.employee_number, '000789');
        await openProfile('basic');
        await page.locator('#profile-personnel_category').selectOption('student');
        await tab('funding').click();
        await expect(page.locator('#project-0-name')).toBeHidden();
        await expect(page.locator('#project-1-name')).toBeHidden();
        await expect(project(0).locator('.profile-project-default input')).toBeChecked();
        await finish();
        const compactHeight = await page.locator('#personalProfileForm').evaluate(element => element.offsetHeight);
        await project(0).locator('.profile-project-toggle').evaluate(button => button.click());
        const projectFrame = time => page.evaluate(time => {
            document.getElementById('personalProfileLayer').getAnimations({ subtree: true }).forEach(animation => { animation.pause(); animation.currentTime = time; });
            const body = document.getElementById('profile-project-body-0');
            return { height: body.getBoundingClientRect().height, naturalHeight: body.scrollHeight,
                opacity: Number(getComputedStyle(body).opacity), modalHeight: document.getElementById('personalProfileForm').offsetHeight };
        }, time);
        const projectStart = await projectFrame(0), projectMid = await projectFrame(80);
        assert(projectStart.height < 1 && Math.abs(projectStart.modalHeight - compactHeight) < 2);
        assert(projectMid.height > 0 && projectMid.height < projectMid.naturalHeight && projectMid.opacity > 0 && projectMid.opacity < 1);
        await project(0).locator('.profile-project-toggle').evaluate(button => button.click());
        const reverseStart = await projectFrame(0);
        assert(Math.abs(reverseStart.height - projectMid.height) < 2, 'funding collapse reversal must start at the visible height');
        await finish();
        await expect(page.locator('#project-0-name')).toBeHidden();
        await expandProject(0);
        await page.locator('#project-0-funding_category').selectOption('non_research');
        await expect(page.locator('#project-0-research_type')).toHaveCount(0);
        await page.locator('#profileAddProject').click();
        await page.locator('#project-2-name').fill('临时项目');
        await project(2).getByRole('button', { name: '移除项目 3' }).click();
        await page.locator('.profile-project').nth(0).getByRole('button', { name: '移除项目 1' }).click();
        await save.click();
        await expect(dialog).not.toHaveClass(/open/);
        assert.equal(record.profile.funding.default_project_id, null);
        assert.equal(record.profile.funding.projects.length, 1);
        assert(Object.values(record.profile.policy_identity).every(value => value === null));
        assert.equal(record.profile.basic_info.employee_number, null);
        console.log('PASS funding accordion animation/reversal, saved cards collapsed, dependency cleanup and project removal');
        await openProfile('funding');
        await expandProject(0);
        await page.locator('#project-0-name').fill('失败时保留的草稿');
        failSave = true; await save.click();
        await expect(page.locator('#personalProfileError')).toContainText('无法保存');
        await expect(dialog).toHaveClass(/open/);
        await expect(page.locator('#project-0-name')).toHaveValue('失败时保留的草稿');
        failSave = false; record.revision += 1; await save.click();
        await expect(page.locator('#personalProfileError')).toContainText('另一页面');
        await page.locator('#personalProfileClose').click();
        await openProfile('funding');
        await expect(page.locator('#project-0-name')).toBeHidden();
        await expandProject(0);
        await expect(page.locator('#project-0-name')).toHaveValue('教学经费');
        await page.locator('#personalProfileClose').click();
        console.log('PASS failed save keeps draft; concurrent edit cannot overwrite');
        await page.setViewportSize({ width: 390, height: 844 });
        await openProfile('funding');
        await expect(dialog).toHaveClass(/open/);
        await finish();
        await expect(page.locator('#project-0-name')).toBeHidden();
        await page.screenshot({ path: path.join(output, 'funding-compact-mobile.png'), animations: 'disabled' });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await expandProject(0);
        await expect(page.locator('#project-0-name')).toHaveValue('教学经费');
        await page.evaluate(() => document.documentElement.dataset.motion = 'off');
        await project(0).locator('.profile-project-done').click();
        await expect(page.locator('#project-0-name')).toBeHidden();
        assert.equal(await dialog.evaluate(node => node.getAnimations({ subtree: true }).filter(animation => animation.playState === 'running').length), 0);
        await page.evaluate(() => document.documentElement.removeAttribute('data-motion'));
        await page.locator('#personalProfileClose').click();
        await page.setViewportSize({ width: 1440, height: 1000 });
        console.log('PASS compact funding on mobile and instant collapse when motion is disabled');
        record = { profile: blank(), revision: 0, onboarding_status: 'pending' };
        await page.reload();
        await expect(dialog).toHaveClass(/open/);
        await page.locator('#personalProfileSkip').click();
        await expect(dialog).not.toHaveClass(/open/);
        await page.reload();
        await expect(page.locator('#initOverlay')).toBeHidden();
        await expect(page.locator('#profileBasicSummary')).toHaveText('待补充');
        assert.equal(record.onboarding_status, 'skipped');
        await expect(dialog).not.toHaveClass(/open/);
        console.log('PASS skip persists across page loads');
        await page.setViewportSize({ width: 390, height: 844 });
        await openSettings();
        await openProfile('basic');
        await expect(dialog).toHaveClass(/open/);
        await expect(page.locator('#profile-personnel_category')).toBeVisible();
        await page.screenshot({ path: path.join(output, 'mobile-basic.png'), animations: 'disabled' });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        const bounds = await page.locator('.personal-profile-modal').boundingBox();
        assert(bounds.x >= 0 && bounds.y >= 0 && bounds.y + bounds.height <= 844);
        await page.locator('#personalProfileClose').focus();
        await page.keyboard.press('Shift+Tab');
        await expect(save).toBeFocused();
        await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
        await page.screenshot({ path: path.join(output, 'mobile-dark.png'), animations: 'disabled' });
        await page.keyboard.press('Escape');
        await expect(dialog).not.toHaveClass(/open/);
        console.log('PASS responsive layout, dark mode and keyboard focus');
        await openProfile('basic');
        await expect(dialog).toHaveClass(/open/);
        await page.evaluate(() => document.documentElement.dataset.motion = 'off');
        await page.locator('#profile-personnel_category').selectOption('student');
        await expect(page.locator('[data-profile-ghost]')).toHaveCount(0);
        assert.equal(await page.locator('#profile-student_number').evaluate(input => getComputedStyle(input.parentElement).opacity), '1');
        assert.equal(await dialog.evaluate(node => node.getAnimations({ subtree: true }).filter(animation => animation.playState === 'running').length), 0);
        await page.evaluate(() => document.documentElement.removeAttribute('data-motion'));
        await page.emulateMedia({ reducedMotion: 'reduce' });
        await page.locator('#profile-personnel_category').selectOption('staff');
        assert.equal(await dialog.evaluate(node => node.getAnimations({ subtree: true }).filter(animation => animation.playState === 'running').length), 0);
        console.log('PASS motion toggle and reduced-motion preference settle immediately');
        assert.deepEqual(errors, []);
        console.log('PASS no browser exceptions;', writes.length, 'profile writes');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
